services:

  spring-wildfly:
    build: spring
    ports:
      - '8444:8443'
      - '9990:9990'
    environment:
      JAVA_OPTS_APPEND: >
        -Djavax.net.ssl.trustStore=/opt/jboss/wildfly/standalone/configuration/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    container_name: soa-spring-wildfly
    depends_on:
      - postgres

  jaxrs-wildfly:
    build: jax-rs
    ports:
      - '8445:8443'
      - '9991:9990'
    environment:
      JAVA_OPTS_APPEND: >
        -Djavax.net.ssl.trustStore=/opt/jboss/wildfly/standalone/configuration/truststore.jks
        -Djavax.net.ssl.trustStorePassword=changeit
    container_name: soa-jaxrs-wildfly
    depends_on:
      - spring-wildfly

  frontend:
    build: frontend
    ports:
      - '8448:443'
    container_name: soa-frontend
    depends_on:
      - spring-wildfly
      - jaxrs-wildfly

  postgres:
    image: 'postgres:latest'
    environment:
      - 'PGPORT=5432'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    container_name: soa-db

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8180:8080"
    environment:
      SWAGGER_JSON: /mnt/openapi.yaml
    volumes:
      - ./openapi.yaml:/mnt/openapi.yaml
    container_name: soa-swagger
    depends_on:
      - frontend

volumes:
  postgresql-data:
