services:

  spring-wildfly:
    build: spring
    ports:
      - '8443:8443'
      - '9990:9990'
    container_name: soa-spring-wildfly
    depends_on:
      - postgres

  postgres:
    image: 'postgres:latest'
    environment:
      - 'PGPORT=5432'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    container_name: soa-db

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /mnt/openapi.yaml
    volumes:
      - ./openapi.yaml:/mnt/openapi.yaml
    container_name: soa-swagger

volumes:
  postgresql-data:
